export const GET_POKEMONS = "GET_POKEMONS"
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME"
export const FILTER_BY_TYPE = "FILTER_BY_TYPE"
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN"
export const ORDER = "ORDER"
export const CREATE_POKEMON = 'CREATE_POKEMON'
export const GET_TYPES = 'GET_TYPES'
